# Generated by Django 5.1 on 2024-08-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
