# Generated by Django 5.1 on 2024-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام نمایشی لینک (مانند YouTube, Instagram و غیره).', max_length=100)),
                ('url', models.URLField(help_text='آدرس کامل لینک.', max_length=255)),
                ('icon_class', models.CharField(help_text="کلاس CSS برای آیکون (مانند 'fab fa-youtube').", max_length=100)),
            ],
        ),
    ]
